base_admin_account:
    resource: "@BaseAdminBundle/Resources/config/routing/admin.yml"
    prefix: /

base_admin_ajax:
    resource: "@BaseAdminBundle/Resources/config/routing/api-routing.yml"
    prefix: /api