base_admin_account:
    resource: "@BaseAdminBundle/Resources/config/routing/account.yml"
    prefix: /admin

base_admin_ajax:
    resource: "@BaseAdminBundle/Resources/config/routing/api-routing.yml"
    prefix: /api