Base\AdminBundle\Entity\Account:
    type: entity
    table: tblAccount
    repositoryClass: Base\AdminBundle\Repository\Doctrine\AccountRepository
    id:
        id:
            type: string
            length: 255
    fields:
        name:
            type: string
            nullable: true
            length: 255
            column: name
        email:
            type: string
            nullable: true
            length: 255
            column: email
        username:
            type: string
            nullable: true
            length: 255
            column: username
        password:
            type: string
            nullable: true
            length: 255
            column: password
        active:
            type: boolean
            column: active
        removedRecord:
            type: boolean
            column: removedRecord
        createdDate:
            type: datetime
            nullable: true
            column: createdDate
        updatedDate:
            type: datetime
            nullable: true
            column: updatedDate