Base\AdminBundle\Entity\Category:
    type: entity
    table: tblCategory
    repositoryClass: Base\AdminBundle\Repository\Doctrine\CategoryRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            nullable: true
            length: 255
            column: name
        parentId:
            type: integer
            column: parentId
        active:
            type: boolean
            column: active
        removedRecord:
            type: boolean
            column: removedRecord
        createdDate:
            type: datetime
            nullable: true
            column: createdDate
        updatedDate:
            type: datetime
            nullable: true
            column: updatedDate