Base\AdminBundle\Entity\Category:
    type: entity
    table: tblCategory
    repositoryClass: Base\AdminBundle\Repository\Doctrine\CategoryRepository
    id:
        id:
            type: string
            length: 255
    fields:
        name:
            type: string
            nullable: true
            length: 255
            column: name
        slug:
            type: string
            nullable: true
            length: 255
            column: slug
        parentId:
            type: string
            length: 255
            column: parentId
        seoTitle:
            type: string
            nullable: true
            length: 255
            column: seoTitle
        seoDescription:
            type: string
            nullable: true
            length: 255
            column: seoDescription
        seoKeyword:
            type: string
            nullable: true
            length: 255
            column: seoKeyword
        active:
            type: boolean
            column: active
        removedRecord:
            type: boolean
            column: removedRecord
        createdDate:
            type: datetime
            nullable: true
            column: createdDate
        updatedDate:
            type: datetime
            nullable: true
            column: updatedDate