base_admin_account_index:
  path: /
  defaults: { _controller: BaseAdminBundle:Account:index }

base_admin_account_update:
  path: /update/{id}
  defaults: { _controller: BaseAdminBundle:Account:update, id: 0 }
  methods: [GET, POST]
  requirements:
            id:  \d+

base_admin_account_delete:
  path: /delete/{id}
  defaults: { _controller: BaseAdminBundle:Account:delete }
  methods: [GET, POST]
  requirements:
          id:  \d+