base_admin_dashboard:
  path: /
  defaults: { _controller: BaseAdminBundle:Dashboard:index }

base_admin_dashboard_login:
  path: /login
  defaults: { _controller: BaseAdminBundle:Dashboard:login }

base_admin_account_index:
  path: /account
  defaults: { _controller: BaseAdminBundle:Account:index }

base_admin_account_update:
  path: /account/update/{id}
  defaults: { _controller: BaseAdminBundle:Account:update, id: 0 }
  methods: [GET]
  requirements:
            id:  \d+

base_admin_category_index:
  path: /category
  defaults: { _controller: BaseAdminBundle:Category:index }

base_admin_category_update:
  path: /category/update/{id}
  defaults: { _controller: BaseAdminBundle:Category:update, id: 0 }
  methods: [GET]
  requirements:
            id:  \d+

base_admin_product_index:
  path: /product
  defaults: { _controller: BaseAdminBundle:Product:index }

base_admin_product_update:
  path: /product/update/{id}
  defaults: { _controller: BaseAdminBundle:Product:update, id: 0 }
  methods: [GET]
  requirements:
            id:  \d+

