<?php

namespace Base\AdminBundle\Repository;

/**
 * TableAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableAccountRepository extends \Doctrine\ORM\EntityRepository
{
}
